-- USER_TYPE Table
CREATE TABLE USER_TYPE (
    user_type_id NUMBER PRIMARY KEY,
    user_type_name VARCHAR(50) UNIQUE NOT NULL
);

-- HOTEL Table
CREATE TABLE HOTEL (
    hotel_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    address VARCHAR(50),
    room_num NUMBER,
    amenities VARCHAR(255)
);

-- SYSTEM_USER Table
CREATE TABLE SYSTEM_USER (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(50) NOT NULL,
    user_type NUMBER,
    hotel_id NUMBER NULL, -- Allowed null for system administrator
    FOREIGN KEY (hotel_id) REFERENCES HOTEL (hotel_id),
    FOREIGN KEY (user_type) REFERENCES USER_TYPE(user_type_id)
);

-- CUSTOMER Table
-- When a new hotel is added to the table, a guest user for the new hotel must also be added into SYSTEM_USER
CREATE TABLE CUSTOMER (
    customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    phone NUMBER,
    email VARCHAR(50)
);

-- ROOM_TYPE Table
CREATE TABLE ROOM_TYPE (
    type_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_name VARCHAR(50) NOT NULL
);

-- ROOM Table
CREATE TABLE ROOM (
    room_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_num NUMBER,
    hotel_id NUMBER,
    type NUMBER,
    price DECIMAL(10,2),
    floor NUMBER,
    availability CHAR(1) DEFAULT 'Y', -- 'Y' for available, 'N' for not available
    FOREIGN KEY (hotel_id) REFERENCES HOTEL(hotel_id),
    FOREIGN KEY (type) REFERENCES ROOM_TYPE(type_id)
);

-- RESERVATION Table
CREATE TABLE RESERVATION (
    reservation_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id NUMBER,
    room_id NUMBER,
    check_in_date DATE,
    check_out_date DATE,
    cost DECIMAL(10,2),
    FOREIGN KEY (customer_id) REFERENCES CUSTOMER(customer_id),
    FOREIGN KEY (room_id) REFERENCES ROOM(room_id)
);

-- HOTEL_LOGS Table
CREATE TABLE HOTEL_LOGS (
    log_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name VARCHAR(50),
    action_type VARCHAR(50),
    action_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    user_name VARCHAR(50),
    details VARCHAR(255)
);

-----------------------------------------------
-- Insert Data into ROOM_TYPE
INSERT INTO ROOM_TYPE (type_name) VALUES 
('Single'),
('Double'),
('Suite'),
('Deluxe'),
('Family');

