@startuml

package gui {
    class AboutFrame
    class CreateReservationFrame
    class CustomerFrame
    class deleteUser
    class HelpFrame
    class HotelFrame
    class LoginFrame
    class MainFrame
    class ReservationFrame
    class RoomActionsFrame
    class RoomFrame
    class StartingFrame
    class UserFrame
    class UserManagmentFrame
}

StartingFrame --|> LoginFrame : follows
LoginFrame --|> MainFrame : follows

MainFrame <-- AboutFrame : contained
MainFrame <-- CreateReservationFrame : contained
MainFrame <-- CustomerFrame : contained
MainFrame <-- deleteUser : contained
MainFrame <-- HelpFrame : contained
MainFrame <-- HotelFrame : contained
MainFrame <-- MainFrame : contained
MainFrame <-- ReservationFrame : contained
MainFrame <-- RoomActionsFrame : contained
MainFrame <-- RoomFrame : contained
MainFrame <-- UserFrame : contained
MainFrame <-- UserManagmentFrame : contained

@enduml
