@startuml gui

package gui {
    class AboutFrame
    class CreateReservationFrame
    class CustomerFrame
    class deleteUser
    class HelpFrame
    class HotelFrame
    class LoginFrame
    class MainFrame
    class ReservationFrame
    class RoomActionsFrame
    class RoomFrame
    class StartingFrame
    class UserFrame
}

StartingFrame --> LoginFrame : follows
LoginFrame --> MainFrame : follows

MainFrame o--> AboutFrame : contains
MainFrame o--> CreateReservationFrame : contains
MainFrame o--> CustomerFrame : contains
MainFrame o--> deleteUser : contains
MainFrame o--> HelpFrame : contains
MainFrame o--> HotelFrame : contains
MainFrame o--> ReservationFrame : contains
MainFrame o--> RoomActionsFrame : contains
MainFrame o--> RoomFrame : contains
MainFrame o--> UserFrame : contains

@enduml
